#!/usr/bin/env python2.6
"""
@author: Bryan Silverthorn <bcs@cargo-cult.org>
"""

if __name__ == "__main__":
    import sys

    from os.path    import join
    from borg_shell import (
        execute_borg,
        get_default_root,
        )

    (instance, seed) = sys.argv[1:]

    execute_borg(
        support   = "ext",
        submodule = "src/dep",
        as_module = True,
        argv      = [
            "borg.tools.portfolio.solve",
            "-v",
            "-m",
            join(get_default_root(), "ext/dcm_model.pickle"),
            "--seed",
            seed,
            instance,
            ],
        )

